[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64", "setuptools_scm>=8"]

[project]
authors = [
    {email = "hello@futurehouse.org", name = "FutureHouse technical staff"},
]
dependencies = [
    "aviary.litqa",
    "fh-llm-client",
    "fhaviary",
    "paper-qa",
    "pydantic~=2.0",
]
description = "LFRQA environment implemented with aviary"
dynamic = ["version"]
name = "aviary.lfrqa"
readme = "README.md"
requires-python = ">=3.11"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
root = "../.."
version_file = "src/aviary/envs/lfrqa/version.py"
