import ahocorasick

ENZYMES: dict[str, dict[str, str | int]] = {
    "AanI": {
        "name": "AanI",
        "regexp_for": "TTATAA",
        "regexp_rev": "TTATAA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TTATAA",
    },
    "AarI": {
        "name": "AarI",
        "regexp_for": "CACCTGC",
        "regexp_rev": "GCAGGTG",
        "skip": 4,
        "overhead_length": 4,
        "recognition_site": "CACCTGC",
    },
    "AasI": {
        "name": "AasI",
        "regexp_for": "GACNNNNNNGTC",
        "regexp_rev": "GACNNNNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNNNNGTC",
    },
    "AatII": {
        "name": "AatII",
        "regexp_for": "GACGTC",
        "regexp_rev": "GACGTC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GACGTC",
    },
    "AccI": {
        "name": "AccI",
        "regexp_for": "GTMKAC",
        "regexp_rev": "GTMKAC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GTMKAC",
    },
    "Acc65I": {
        "name": "Acc65I",
        "regexp_for": "GGTACC",
        "regexp_rev": "GGTACC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGTACC",
    },
    "AciI": {
        "name": "AciI",
        "regexp_for": "CCGC",
        "regexp_rev": "GCGG",
        "skip": -3,
        "overhead_length": 2,
        "recognition_site": "CCGC",
    },
    "AclI": {
        "name": "AclI",
        "regexp_for": "AACGTT",
        "regexp_rev": "AACGTT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "AACGTT",
    },
    "AcuI": {
        "name": "AcuI",
        "regexp_for": "CTGAAG",
        "regexp_rev": "CTTCAG",
        "skip": 16,
        "overhead_length": -2,
        "recognition_site": "CTGAAG",
    },
    "AdeI": {
        "name": "AdeI",
        "regexp_for": "CACNNNGTG",
        "regexp_rev": "CACNNNGTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CACNNNGTG",
    },
    "AfaI": {
        "name": "AfaI",
        "regexp_for": "GTAC",
        "regexp_rev": "GTAC",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "GTAC",
    },
    "AfeI": {
        "name": "AfeI",
        "regexp_for": "AGCGCT",
        "regexp_rev": "AGCGCT",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "AGCGCT",
    },
    "AflII": {
        "name": "AflII",
        "regexp_for": "CTTAAG",
        "regexp_rev": "CTTAAG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CTTAAG",
    },
    "AflIII": {
        "name": "AflIII",
        "regexp_for": "ACRYGT",
        "regexp_rev": "ACRYGT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "ACRYGT",
    },
    "AgeI": {
        "name": "AgeI",
        "regexp_for": "ACCGGT",
        "regexp_rev": "ACCGGT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "ACCGGT",
    },
    "AhdI": {
        "name": "AhdI",
        "regexp_for": "GACNNNNNGTC",
        "regexp_rev": "GACNNNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNNNGTC",
    },
    "AjiI": {
        "name": "AjiI",
        "regexp_for": "CACGTC",
        "regexp_rev": "GACGTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CACGTC",
    },
    "AleI": {
        "name": "AleI",
        "regexp_for": "CACNNNNGTG",
        "regexp_rev": "CACNNNNGTG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CACNNNNGTG",
    },
    "AluI": {
        "name": "AluI",
        "regexp_for": "AGCT",
        "regexp_rev": "AGCT",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "AGCT",
    },
    "AlwI": {
        "name": "AlwI",
        "regexp_for": "GGATC",
        "regexp_rev": "GATCC",
        "skip": 4,
        "overhead_length": 1,
        "recognition_site": "GGATC",
    },
    "Alw21I": {
        "name": "Alw21I",
        "regexp_for": "GWGCWC",
        "regexp_rev": "GWGCWC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GWGCWC",
    },
    "Alw26I": {
        "name": "Alw26I",
        "regexp_for": "GTCTC",
        "regexp_rev": "GAGAC",
        "skip": 1,
        "overhead_length": 4,
        "recognition_site": "GTCTC",
    },
    "Alw44I": {
        "name": "Alw44I",
        "regexp_for": "GTGCAC",
        "regexp_rev": "GTGCAC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GTGCAC",
    },
    "AlwNI": {
        "name": "AlwNI",
        "regexp_for": "CAGNNNCTG",
        "regexp_rev": "CAGNNNCTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CAGNNNCTG",
    },
    "ApaI": {
        "name": "ApaI",
        "regexp_for": "GGGCCC",
        "regexp_rev": "GGGCCC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GGGCCC",
    },
    "ApaLI": {
        "name": "ApaLI",
        "regexp_for": "GTGCAC",
        "regexp_rev": "GTGCAC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GTGCAC",
    },
    "ApeKI": {
        "name": "ApeKI",
        "regexp_for": "GCWGC",
        "regexp_rev": "GCWGC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GCWGC",
    },
    "ApoI": {
        "name": "ApoI",
        "regexp_for": "RAATTY",
        "regexp_rev": "RAATTY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RAATTY",
    },
    "AscI": {
        "name": "AscI",
        "regexp_for": "GGCGCGCC",
        "regexp_rev": "GGCGCGCC",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "GGCGCGCC",
    },
    "AseI": {
        "name": "AseI",
        "regexp_for": "ATTAAT",
        "regexp_rev": "ATTAAT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "ATTAAT",
    },
    "AsiSI": {
        "name": "AsiSI",
        "regexp_for": "GCGATCGC",
        "regexp_rev": "GCGATCGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCGATCGC",
    },
    "AvaI": {
        "name": "AvaI",
        "regexp_for": "CYCGRG",
        "regexp_rev": "CYCGRG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CYCGRG",
    },
    "AvaII": {
        "name": "AvaII",
        "regexp_for": "GGWCC",
        "regexp_rev": "GGWCC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GGWCC",
    },
    "AvrII": {
        "name": "AvrII",
        "regexp_for": "CCTAGG",
        "regexp_rev": "CCTAGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCTAGG",
    },
    "BaeGI": {
        "name": "BaeGI",
        "regexp_for": "GKGCMC",
        "regexp_rev": "GKGCMC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GKGCMC",
    },
    "BalI": {
        "name": "BalI",
        "regexp_for": "TGGCCA",
        "regexp_rev": "TGGCCA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TGGCCA",
    },
    "BamHI": {
        "name": "BamHI",
        "regexp_for": "GGATCC",
        "regexp_rev": "GGATCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGATCC",
    },
    "BanI": {
        "name": "BanI",
        "regexp_for": "GGYRCC",
        "regexp_rev": "GGYRCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGYRCC",
    },
    "BanII": {
        "name": "BanII",
        "regexp_for": "GRGCYC",
        "regexp_rev": "GRGCYC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GRGCYC",
    },
    "BauI": {
        "name": "BauI",
        "regexp_for": "CACGAG",
        "regexp_rev": "CTCGTG",
        "skip": -5,
        "overhead_length": 4,
        "recognition_site": "CACGAG",
    },
    "BbsI": {
        "name": "BbsI",
        "regexp_for": "GAAGAC",
        "regexp_rev": "GTCTTC",
        "skip": 2,
        "overhead_length": 4,
        "recognition_site": "GAAGAC",
    },
    "BbvI": {
        "name": "BbvI",
        "regexp_for": "GCAGC",
        "regexp_rev": "GCTGC",
        "skip": 8,
        "overhead_length": 4,
        "recognition_site": "GCAGC",
    },
    "BbvCI": {
        "name": "BbvCI",
        "regexp_for": "CCTCAGC",
        "regexp_rev": "GCTGAGG",
        "skip": -5,
        "overhead_length": 3,
        "recognition_site": "CCTCAGC",
    },
    "BccI": {
        "name": "BccI",
        "regexp_for": "CCATC",
        "regexp_rev": "GATGG",
        "skip": 4,
        "overhead_length": 1,
        "recognition_site": "CCATC",
    },
    "BceAI": {
        "name": "BceAI",
        "regexp_for": "ACGGC",
        "regexp_rev": "GCCGT",
        "skip": 12,
        "overhead_length": 2,
        "recognition_site": "ACGGC",
    },
    "BciVI": {
        "name": "BciVI",
        "regexp_for": "GTATCC",
        "regexp_rev": "GGATAC",
        "skip": 6,
        "overhead_length": -1,
        "recognition_site": "GTATCC",
    },
    "BclI": {
        "name": "BclI",
        "regexp_for": "TGATCA",
        "regexp_rev": "TGATCA",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "TGATCA",
    },
    "BcnI": {
        "name": "BcnI",
        "regexp_for": "CCSGG",
        "regexp_rev": "CCSGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCSGG",
    },
    "BcoDI": {
        "name": "BcoDI",
        "regexp_for": "GTCTC",
        "regexp_rev": "GAGAC",
        "skip": 1,
        "overhead_length": 4,
        "recognition_site": "GTCTC",
    },
    "BcuI": {
        "name": "BcuI",
        "regexp_for": "ACTAGT",
        "regexp_rev": "ACTAGT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "ACTAGT",
    },
    "BfaI": {
        "name": "BfaI",
        "regexp_for": "CTAG",
        "regexp_rev": "CTAG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CTAG",
    },
    "BfmI": {
        "name": "BfmI",
        "regexp_for": "CTRYAG",
        "regexp_rev": "CTRYAG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CTRYAG",
    },
    "BfoI": {
        "name": "BfoI",
        "regexp_for": "RGCGCY",
        "regexp_rev": "RGCGCY",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "RGCGCY",
    },
    "BfuI": {
        "name": "BfuI",
        "regexp_for": "GTATCC",
        "regexp_rev": "GGATAC",
        "skip": 6,
        "overhead_length": -1,
        "recognition_site": "GTATCC",
    },
    "BfuAI": {
        "name": "BfuAI",
        "regexp_for": "ACCTGC",
        "regexp_rev": "GCAGGT",
        "skip": 4,
        "overhead_length": 4,
        "recognition_site": "ACCTGC",
    },
    "BglI": {
        "name": "BglI",
        "regexp_for": "GCCNNNNNGGC",
        "regexp_rev": "GCCNNNNNGGC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GCCNNNNNGGC",
    },
    "BglII": {
        "name": "BglII",
        "regexp_for": "AGATCT",
        "regexp_rev": "AGATCT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "AGATCT",
    },
    "BlpI": {
        "name": "BlpI",
        "regexp_for": "GCTNAGC",
        "regexp_rev": "GCTNAGC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GCTNAGC",
    },
    "Bme1390I": {
        "name": "Bme1390I",
        "regexp_for": "CCNGG",
        "regexp_rev": "CCNGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCNGG",
    },
    "BmeT110I": {
        "name": "BmeT110I",
        "regexp_for": "CYCGRG",
        "regexp_rev": "CYCGRG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CYCGRG",
    },
    "BmgBI": {
        "name": "BmgBI",
        "regexp_for": "CACGTC",
        "regexp_rev": "GACGTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CACGTC",
    },
    "BmrI": {
        "name": "BmrI",
        "regexp_for": "ACTGGG",
        "regexp_rev": "CCCAGT",
        "skip": 5,
        "overhead_length": -1,
        "recognition_site": "ACTGGG",
    },
    "BmsI": {
        "name": "BmsI",
        "regexp_for": "GCATC",
        "regexp_rev": "GATGC",
        "skip": 5,
        "overhead_length": 4,
        "recognition_site": "GCATC",
    },
    "BmtI": {
        "name": "BmtI",
        "regexp_for": "GCTAGC",
        "regexp_rev": "GCTAGC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GCTAGC",
    },
    "BoxI": {
        "name": "BoxI",
        "regexp_for": "GACNNNNGTC",
        "regexp_rev": "GACNNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNNGTC",
    },
    "BpiI": {
        "name": "BpiI",
        "regexp_for": "GAAGAC",
        "regexp_rev": "GTCTTC",
        "skip": 2,
        "overhead_length": 4,
        "recognition_site": "GAAGAC",
    },
    "BpmI": {
        "name": "BpmI",
        "regexp_for": "CTGGAG",
        "regexp_rev": "CTCCAG",
        "skip": 16,
        "overhead_length": -2,
        "recognition_site": "CTGGAG",
    },
    "Bpu10I": {
        "name": "Bpu10I",
        "regexp_for": "CCTNAGC",
        "regexp_rev": "GCTNAGG",
        "skip": -5,
        "overhead_length": 3,
        "recognition_site": "CCTNAGC",
    },
    "Bpu1102I": {
        "name": "Bpu1102I",
        "regexp_for": "GCTNAGC",
        "regexp_rev": "GCTNAGC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GCTNAGC",
    },
    "BpuEI": {
        "name": "BpuEI",
        "regexp_for": "CTTGAG",
        "regexp_rev": "CTCAAG",
        "skip": 16,
        "overhead_length": -2,
        "recognition_site": "CTTGAG",
    },
    "BsaI": {
        "name": "BsaI",
        "regexp_for": "GGTCTC",
        "regexp_rev": "GAGACC",
        "skip": 1,
        "overhead_length": 4,
        "recognition_site": "GGTCTC",
    },
    "BsaAI": {
        "name": "BsaAI",
        "regexp_for": "YACGTR",
        "regexp_rev": "YACGTR",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "YACGTR",
    },
    "BsaBI": {
        "name": "BsaBI",
        "regexp_for": "GATNNNNATC",
        "regexp_rev": "GATNNNNATC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GATNNNNATC",
    },
    "BsaHI": {
        "name": "BsaHI",
        "regexp_for": "GRCGYC",
        "regexp_rev": "GRCGYC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GRCGYC",
    },
    "BsaJI": {
        "name": "BsaJI",
        "regexp_for": "CCNNGG",
        "regexp_rev": "CCNNGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCNNGG",
    },
    "BsaWI": {
        "name": "BsaWI",
        "regexp_for": "WCCGGW",
        "regexp_rev": "WCCGGW",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "WCCGGW",
    },
    "BseDI": {
        "name": "BseDI",
        "regexp_for": "CCNNGG",
        "regexp_rev": "CCNNGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCNNGG",
    },
    "BseGI": {
        "name": "BseGI",
        "regexp_for": "GGATG",
        "regexp_rev": "CATCC",
        "skip": 2,
        "overhead_length": -2,
        "recognition_site": "GGATG",
    },
    "BseJI": {
        "name": "BseJI",
        "regexp_for": "GATNNNNATC",
        "regexp_rev": "GATNNNNATC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GATNNNNATC",
    },
    "BseLI": {
        "name": "BseLI",
        "regexp_for": "CCNNNNNNNGG",
        "regexp_rev": "CCNNNNNNNGG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CCNNNNNNNGG",
    },
    "BseMI": {
        "name": "BseMI",
        "regexp_for": "GCAATG",
        "regexp_rev": "CATTGC",
        "skip": 2,
        "overhead_length": -2,
        "recognition_site": "GCAATG",
    },
    "BseMII": {
        "name": "BseMII",
        "regexp_for": "CTCAG",
        "regexp_rev": "CTGAG",
        "skip": 10,
        "overhead_length": -2,
        "recognition_site": "CTCAG",
    },
    "BseNI": {
        "name": "BseNI",
        "regexp_for": "ACTGG",
        "regexp_rev": "CCAGT",
        "skip": 1,
        "overhead_length": -2,
        "recognition_site": "ACTGG",
    },
    "BseRI": {
        "name": "BseRI",
        "regexp_for": "GAGGAG",
        "regexp_rev": "CTCCTC",
        "skip": 10,
        "overhead_length": -2,
        "recognition_site": "GAGGAG",
    },
    "BseSI": {
        "name": "BseSI",
        "regexp_for": "GKGCMC",
        "regexp_rev": "GKGCMC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GKGCMC",
    },
    "BseXI": {
        "name": "BseXI",
        "regexp_for": "GCAGC",
        "regexp_rev": "GCTGC",
        "skip": 8,
        "overhead_length": 4,
        "recognition_site": "GCAGC",
    },
    "BseYI": {
        "name": "BseYI",
        "regexp_for": "CCCAGC",
        "regexp_rev": "GCTGGG",
        "skip": -5,
        "overhead_length": 4,
        "recognition_site": "CCCAGC",
    },
    "BsgI": {
        "name": "BsgI",
        "regexp_for": "GTGCAG",
        "regexp_rev": "CTGCAC",
        "skip": 16,
        "overhead_length": -2,
        "recognition_site": "GTGCAG",
    },
    "Bsh1236I": {
        "name": "Bsh1236I",
        "regexp_for": "CGCG",
        "regexp_rev": "CGCG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CGCG",
    },
    "Bsh1285I": {
        "name": "Bsh1285I",
        "regexp_for": "CGRYCG",
        "regexp_rev": "CGRYCG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CGRYCG",
    },
    "BshNI": {
        "name": "BshNI",
        "regexp_for": "GGYRCC",
        "regexp_rev": "GGYRCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGYRCC",
    },
    "BshTI": {
        "name": "BshTI",
        "regexp_for": "ACCGGT",
        "regexp_rev": "ACCGGT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "ACCGGT",
    },
    "BsiEI": {
        "name": "BsiEI",
        "regexp_for": "CGRYCG",
        "regexp_rev": "CGRYCG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CGRYCG",
    },
    "BsiHKAI": {
        "name": "BsiHKAI",
        "regexp_for": "GWGCWC",
        "regexp_rev": "GWGCWC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GWGCWC",
    },
    "BsiWI": {
        "name": "BsiWI",
        "regexp_for": "CGTACG",
        "regexp_rev": "CGTACG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CGTACG",
    },
    "BslI": {
        "name": "BslI",
        "regexp_for": "CCNNNNNNNGG",
        "regexp_rev": "CCNNNNNNNGG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CCNNNNNNNGG",
    },
    "BsmI": {
        "name": "BsmI",
        "regexp_for": "GAATGC",
        "regexp_rev": "GCATTC",
        "skip": 1,
        "overhead_length": -2,
        "recognition_site": "GAATGC",
    },
    "BsmAI": {
        "name": "BsmAI",
        "regexp_for": "GTCTC",
        "regexp_rev": "GAGAC",
        "skip": 1,
        "overhead_length": 4,
        "recognition_site": "GTCTC",
    },
    "BsmBI": {
        "name": "BsmBI",
        "regexp_for": "CGTCTC",
        "regexp_rev": "GAGACG",
        "skip": 1,
        "overhead_length": 4,
        "recognition_site": "CGTCTC",
    },
    "BsmFI": {
        "name": "BsmFI",
        "regexp_for": "GGGAC",
        "regexp_rev": "GTCCC",
        "skip": 10,
        "overhead_length": 4,
        "recognition_site": "GGGAC",
    },
    "BsoBI": {
        "name": "BsoBI",
        "regexp_for": "CYCGRG",
        "regexp_rev": "CYCGRG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CYCGRG",
    },
    "Bsp68I": {
        "name": "Bsp68I",
        "regexp_for": "TCGCGA",
        "regexp_rev": "TCGCGA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TCGCGA",
    },
    "Bsp119I": {
        "name": "Bsp119I",
        "regexp_for": "TTCGAA",
        "regexp_rev": "TTCGAA",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "TTCGAA",
    },
    "Bsp120I": {
        "name": "Bsp120I",
        "regexp_for": "GGGCCC",
        "regexp_rev": "GGGCCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGGCCC",
    },
    "Bsp143I": {
        "name": "Bsp143I",
        "regexp_for": "GATC",
        "regexp_rev": "GATC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GATC",
    },
    "Bsp1286I": {
        "name": "Bsp1286I",
        "regexp_for": "GDGCHC",
        "regexp_rev": "GDGCHC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GDGCHC",
    },
    "Bsp1407I": {
        "name": "Bsp1407I",
        "regexp_for": "TGTACA",
        "regexp_rev": "TGTACA",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "TGTACA",
    },
    "BspCNI": {
        "name": "BspCNI",
        "regexp_for": "CTCAG",
        "regexp_rev": "CTGAG",
        "skip": 9,
        "overhead_length": -2,
        "recognition_site": "CTCAG",
    },
    "BspDI": {
        "name": "BspDI",
        "regexp_for": "ATCGAT",
        "regexp_rev": "ATCGAT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "ATCGAT",
    },
    "BspEI": {
        "name": "BspEI",
        "regexp_for": "TCCGGA",
        "regexp_rev": "TCCGGA",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "TCCGGA",
    },
    "BspHI": {
        "name": "BspHI",
        "regexp_for": "TCATGA",
        "regexp_rev": "TCATGA",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "TCATGA",
    },
    "BspLI": {
        "name": "BspLI",
        "regexp_for": "GGNNCC",
        "regexp_rev": "GGNNCC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GGNNCC",
    },
    "BspMI": {
        "name": "BspMI",
        "regexp_for": "ACCTGC",
        "regexp_rev": "GCAGGT",
        "skip": 4,
        "overhead_length": 4,
        "recognition_site": "ACCTGC",
    },
    "BspOI": {
        "name": "BspOI",
        "regexp_for": "GCTAGC",
        "regexp_rev": "GCTAGC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GCTAGC",
    },
    "BspPI": {
        "name": "BspPI",
        "regexp_for": "GGATC",
        "regexp_rev": "GATCC",
        "skip": 4,
        "overhead_length": 1,
        "recognition_site": "GGATC",
    },
    "BspQI": {
        "name": "BspQI",
        "regexp_for": "GCTCTTC",
        "regexp_rev": "GAAGAGC",
        "skip": 1,
        "overhead_length": 3,
        "recognition_site": "GCTCTTC",
    },
    "BspTI": {
        "name": "BspTI",
        "regexp_for": "CTTAAG",
        "regexp_rev": "CTTAAG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CTTAAG",
    },
    "BsrI": {
        "name": "BsrI",
        "regexp_for": "ACTGG",
        "regexp_rev": "CCAGT",
        "skip": 1,
        "overhead_length": -2,
        "recognition_site": "ACTGG",
    },
    "BsrBI": {
        "name": "BsrBI",
        "regexp_for": "CCGCTC",
        "regexp_rev": "GAGCGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCGCTC",
    },
    "BsrDI": {
        "name": "BsrDI",
        "regexp_for": "GCAATG",
        "regexp_rev": "CATTGC",
        "skip": 2,
        "overhead_length": -2,
        "recognition_site": "GCAATG",
    },
    "BsrFI": {
        "name": "BsrFI",
        "regexp_for": "RCCGGY",
        "regexp_rev": "RCCGGY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RCCGGY",
    },
    "BsrGI": {
        "name": "BsrGI",
        "regexp_for": "TGTACA",
        "regexp_rev": "TGTACA",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "TGTACA",
    },
    "BssHII": {
        "name": "BssHII",
        "regexp_for": "GCGCGC",
        "regexp_rev": "GCGCGC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GCGCGC",
    },
    "BssSI": {
        "name": "BssSI",
        "regexp_for": "CACGAG",
        "regexp_rev": "CTCGTG",
        "skip": -5,
        "overhead_length": 4,
        "recognition_site": "CACGAG",
    },
    "Bst1107I": {
        "name": "Bst1107I",
        "regexp_for": "GTATAC",
        "regexp_rev": "GTATAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTATAC",
    },
    "BstAPI": {
        "name": "BstAPI",
        "regexp_for": "GCANNNNNTGC",
        "regexp_rev": "GCANNNNNTGC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GCANNNNNTGC",
    },
    "BstBI": {
        "name": "BstBI",
        "regexp_for": "TTCGAA",
        "regexp_rev": "TTCGAA",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "TTCGAA",
    },
    "BstEII": {
        "name": "BstEII",
        "regexp_for": "GGTNACC",
        "regexp_rev": "GGTNACC",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "GGTNACC",
    },
    "BstNI": {
        "name": "BstNI",
        "regexp_for": "CCWGG",
        "regexp_rev": "CCWGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCWGG",
    },
    "BstUI": {
        "name": "BstUI",
        "regexp_for": "CGCG",
        "regexp_rev": "CGCG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CGCG",
    },
    "BstXI": {
        "name": "BstXI",
        "regexp_for": "CCANNNNNNTGG",
        "regexp_rev": "CCANNNNNNTGG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CCANNNNNNTGG",
    },
    "BstYI": {
        "name": "BstYI",
        "regexp_for": "RGATCY",
        "regexp_rev": "RGATCY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RGATCY",
    },
    "BstZ17I": {
        "name": "BstZ17I",
        "regexp_for": "GTATAC",
        "regexp_rev": "GTATAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTATAC",
    },
    "Bsu15I": {
        "name": "Bsu15I",
        "regexp_for": "ATCGAT",
        "regexp_rev": "ATCGAT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "ATCGAT",
    },
    "Bsu36I": {
        "name": "Bsu36I",
        "regexp_for": "CCTNAGG",
        "regexp_rev": "CCTNAGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCTNAGG",
    },
    "BsuRI": {
        "name": "BsuRI",
        "regexp_for": "GGCC",
        "regexp_rev": "GGCC",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "GGCC",
    },
    "BtgI": {
        "name": "BtgI",
        "regexp_for": "CCRYGG",
        "regexp_rev": "CCRYGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCRYGG",
    },
    "BtgZI": {
        "name": "BtgZI",
        "regexp_for": "GCGATG",
        "regexp_rev": "CATCGC",
        "skip": 10,
        "overhead_length": 4,
        "recognition_site": "GCGATG",
    },
    "BtsI": {
        "name": "BtsI",
        "regexp_for": "GCAGTG",
        "regexp_rev": "CACTGC",
        "skip": 2,
        "overhead_length": -2,
        "recognition_site": "GCAGTG",
    },
    "BtsIMutI": {
        "name": "BtsIMutI",
        "regexp_for": "CAGTG",
        "regexp_rev": "CACTG",
        "skip": 2,
        "overhead_length": -2,
        "recognition_site": "CAGTG",
    },
    "BtsCI": {
        "name": "BtsCI",
        "regexp_for": "GGATG",
        "regexp_rev": "CATCC",
        "skip": 2,
        "overhead_length": -2,
        "recognition_site": "GGATG",
    },
    "BveI": {
        "name": "BveI",
        "regexp_for": "ACCTGC",
        "regexp_rev": "GCAGGT",
        "skip": 4,
        "overhead_length": 4,
        "recognition_site": "ACCTGC",
    },
    "Cac8I": {
        "name": "Cac8I",
        "regexp_for": "GCNNGC",
        "regexp_rev": "GCNNGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCNNGC",
    },
    "CaiI": {
        "name": "CaiI",
        "regexp_for": "CAGNNNCTG",
        "regexp_rev": "CAGNNNCTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CAGNNNCTG",
    },
    "I-CeuI": {
        "name": "I-CeuI",
        "regexp_for": "TAACTATAACGGTCCTAAGGTAGCGAA",
        "regexp_rev": "TTCGCTACCTTAGGACCGTTATAGTTA",
        "skip": -9,
        "overhead_length": -4,
        "recognition_site": "TAACTATAACGGTCCTAAGGTAGCGAA",
    },
    "Cfr9I": {
        "name": "Cfr9I",
        "regexp_for": "CCCGGG",
        "regexp_rev": "CCCGGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCCGGG",
    },
    "Cfr10I": {
        "name": "Cfr10I",
        "regexp_for": "RCCGGY",
        "regexp_rev": "RCCGGY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RCCGGY",
    },
    "Cfr13I": {
        "name": "Cfr13I",
        "regexp_for": "GGNCC",
        "regexp_rev": "GGNCC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GGNCC",
    },
    "Cfr42I": {
        "name": "Cfr42I",
        "regexp_for": "CCGCGG",
        "regexp_rev": "CCGCGG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CCGCGG",
    },
    "ClaI": {
        "name": "ClaI",
        "regexp_for": "ATCGAT",
        "regexp_rev": "ATCGAT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "ATCGAT",
    },
    "CpoI": {
        "name": "CpoI",
        "regexp_for": "CGGWCCG",
        "regexp_rev": "CGGWCCG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CGGWCCG",
    },
    "CseI": {
        "name": "CseI",
        "regexp_for": "GACGC",
        "regexp_rev": "GCGTC",
        "skip": 5,
        "overhead_length": 5,
        "recognition_site": "GACGC",
    },
    "CsiI": {
        "name": "CsiI",
        "regexp_for": "ACCWGGT",
        "regexp_rev": "ACCWGGT",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "ACCWGGT",
    },
    "Csp6I": {
        "name": "Csp6I",
        "regexp_for": "GTAC",
        "regexp_rev": "GTAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTAC",
    },
    "CviAII": {
        "name": "CviAII",
        "regexp_for": "CATG",
        "regexp_rev": "CATG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CATG",
    },
    "CviKI-1": {
        "name": "CviKI-1",
        "regexp_for": "RGCY",
        "regexp_rev": "RGCY",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "RGCY",
    },
    "CviQI": {
        "name": "CviQI",
        "regexp_for": "GTAC",
        "regexp_rev": "GTAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTAC",
    },
    "DdeI": {
        "name": "DdeI",
        "regexp_for": "CTNAG",
        "regexp_rev": "CTNAG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CTNAG",
    },
    "DpnI": {
        "name": "DpnI",
        "regexp_for": "GATC",
        "regexp_rev": "GATC",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "GATC",
    },
    "DpnII": {
        "name": "DpnII",
        "regexp_for": "GATC",
        "regexp_rev": "GATC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GATC",
    },
    "DraI": {
        "name": "DraI",
        "regexp_for": "TTTAAA",
        "regexp_rev": "TTTAAA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TTTAAA",
    },
    "DraIII": {
        "name": "DraIII",
        "regexp_for": "CACNNNGTG",
        "regexp_rev": "CACNNNGTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CACNNNGTG",
    },
    "DrdI": {
        "name": "DrdI",
        "regexp_for": "GACNNNNNNGTC",
        "regexp_rev": "GACNNNNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNNNNGTC",
    },
    "EaeI": {
        "name": "EaeI",
        "regexp_for": "YGGCCR",
        "regexp_rev": "YGGCCR",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "YGGCCR",
    },
    "EagI": {
        "name": "EagI",
        "regexp_for": "CGGCCG",
        "regexp_rev": "CGGCCG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CGGCCG",
    },
    "Eam1104I": {
        "name": "Eam1104I",
        "regexp_for": "CTCTTC",
        "regexp_rev": "GAAGAG",
        "skip": 1,
        "overhead_length": 3,
        "recognition_site": "CTCTTC",
    },
    "Eam1105I": {
        "name": "Eam1105I",
        "regexp_for": "GACNNNNNGTC",
        "regexp_rev": "GACNNNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNNNGTC",
    },
    "EarI": {
        "name": "EarI",
        "regexp_for": "CTCTTC",
        "regexp_rev": "GAAGAG",
        "skip": 1,
        "overhead_length": 3,
        "recognition_site": "CTCTTC",
    },
    "EciI": {
        "name": "EciI",
        "regexp_for": "GGCGGA",
        "regexp_rev": "TCCGCC",
        "skip": 11,
        "overhead_length": -2,
        "recognition_site": "GGCGGA",
    },
    "Ecl136II": {
        "name": "Ecl136II",
        "regexp_for": "GAGCTC",
        "regexp_rev": "GAGCTC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GAGCTC",
    },
    "Eco24I": {
        "name": "Eco24I",
        "regexp_for": "GRGCYC",
        "regexp_rev": "GRGCYC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GRGCYC",
    },
    "Eco31I": {
        "name": "Eco31I",
        "regexp_for": "GGTCTC",
        "regexp_rev": "GAGACC",
        "skip": 1,
        "overhead_length": 4,
        "recognition_site": "GGTCTC",
    },
    "Eco32I": {
        "name": "Eco32I",
        "regexp_for": "GATATC",
        "regexp_rev": "GATATC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GATATC",
    },
    "Eco47I": {
        "name": "Eco47I",
        "regexp_for": "GGWCC",
        "regexp_rev": "GGWCC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GGWCC",
    },
    "Eco47III": {
        "name": "Eco47III",
        "regexp_for": "AGCGCT",
        "regexp_rev": "AGCGCT",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "AGCGCT",
    },
    "Eco52I": {
        "name": "Eco52I",
        "regexp_for": "CGGCCG",
        "regexp_rev": "CGGCCG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CGGCCG",
    },
    "Eco57I": {
        "name": "Eco57I",
        "regexp_for": "CTGAAG",
        "regexp_rev": "CTTCAG",
        "skip": 16,
        "overhead_length": -2,
        "recognition_site": "CTGAAG",
    },
    "Eco72I": {
        "name": "Eco72I",
        "regexp_for": "CACGTG",
        "regexp_rev": "CACGTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CACGTG",
    },
    "Eco81I": {
        "name": "Eco81I",
        "regexp_for": "CCTNAGG",
        "regexp_rev": "CCTNAGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCTNAGG",
    },
    "Eco88I": {
        "name": "Eco88I",
        "regexp_for": "CYCGRG",
        "regexp_rev": "CYCGRG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CYCGRG",
    },
    "Eco91I": {
        "name": "Eco91I",
        "regexp_for": "GGTNACC",
        "regexp_rev": "GGTNACC",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "GGTNACC",
    },
    "Eco105I": {
        "name": "Eco105I",
        "regexp_for": "TACGTA",
        "regexp_rev": "TACGTA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TACGTA",
    },
    "Eco130I": {
        "name": "Eco130I",
        "regexp_for": "CCWWGG",
        "regexp_rev": "CCWWGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCWWGG",
    },
    "Eco147I": {
        "name": "Eco147I",
        "regexp_for": "AGGCCT",
        "regexp_rev": "AGGCCT",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "AGGCCT",
    },
    "EcoNI": {
        "name": "EcoNI",
        "regexp_for": "CCTNNNNNAGG",
        "regexp_rev": "CCTNNNNNAGG",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "CCTNNNNNAGG",
    },
    "EcoO109I": {
        "name": "EcoO109I",
        "regexp_for": "RGGNCCY",
        "regexp_rev": "RGGNCCY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RGGNCCY",
    },
    "EcoP15I": {
        "name": "EcoP15I",
        "regexp_for": "CAGCAG",
        "regexp_rev": "CTGCTG",
        "skip": 25,
        "overhead_length": 2,
        "recognition_site": "CAGCAG",
    },
    "EcoRI": {
        "name": "EcoRI",
        "regexp_for": "GAATTC",
        "regexp_rev": "GAATTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GAATTC",
    },
    "EcoRII": {
        "name": "EcoRII",
        "regexp_for": "CCWGG",
        "regexp_rev": "CCWGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCWGG",
    },
    "EcoRV": {
        "name": "EcoRV",
        "regexp_for": "GATATC",
        "regexp_rev": "GATATC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GATATC",
    },
    "EcoT22I": {
        "name": "EcoT22I",
        "regexp_for": "ATGCAT",
        "regexp_rev": "ATGCAT",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "ATGCAT",
    },
    "Eco53kI": {
        "name": "Eco53kI",
        "regexp_for": "GAGCTC",
        "regexp_rev": "GAGCTC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GAGCTC",
    },
    "EheI": {
        "name": "EheI",
        "regexp_for": "GGCGCC",
        "regexp_rev": "GGCGCC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GGCGCC",
    },
    "Esp3I": {
        "name": "Esp3I",
        "regexp_for": "CGTCTC",
        "regexp_rev": "GAGACG",
        "skip": 1,
        "overhead_length": 4,
        "recognition_site": "CGTCTC",
    },
    "FaqI": {
        "name": "FaqI",
        "regexp_for": "GGGAC",
        "regexp_rev": "GTCCC",
        "skip": 10,
        "overhead_length": 4,
        "recognition_site": "GGGAC",
    },
    "FatI": {
        "name": "FatI",
        "regexp_for": "CATG",
        "regexp_rev": "CATG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CATG",
    },
    "FauI": {
        "name": "FauI",
        "regexp_for": "CCCGC",
        "regexp_rev": "GCGGG",
        "skip": 4,
        "overhead_length": 2,
        "recognition_site": "CCCGC",
    },
    "Fnu4HI": {
        "name": "Fnu4HI",
        "regexp_for": "GCNGC",
        "regexp_rev": "GCNGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCNGC",
    },
    "FokI": {
        "name": "FokI",
        "regexp_for": "GGATG",
        "regexp_rev": "CATCC",
        "skip": 9,
        "overhead_length": 4,
        "recognition_site": "GGATG",
    },
    "FseI": {
        "name": "FseI",
        "regexp_for": "GGCCGGCC",
        "regexp_rev": "GGCCGGCC",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "GGCCGGCC",
    },
    "FspI": {
        "name": "FspI",
        "regexp_for": "TGCGCA",
        "regexp_rev": "TGCGCA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TGCGCA",
    },
    "FspAI": {
        "name": "FspAI",
        "regexp_for": "RTGCGCAY",
        "regexp_rev": "RTGCGCAY",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "RTGCGCAY",
    },
    "FspBI": {
        "name": "FspBI",
        "regexp_for": "CTAG",
        "regexp_rev": "CTAG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CTAG",
    },
    "FspEI": {
        "name": "FspEI",
        "regexp_for": "CC",
        "regexp_rev": "GG",
        "skip": 12,
        "overhead_length": 4,
        "recognition_site": "CC",
    },
    "GsuI": {
        "name": "GsuI",
        "regexp_for": "CTGGAG",
        "regexp_rev": "CTCCAG",
        "skip": 16,
        "overhead_length": -2,
        "recognition_site": "CTGGAG",
    },
    "HaeII": {
        "name": "HaeII",
        "regexp_for": "RGCGCY",
        "regexp_rev": "RGCGCY",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "RGCGCY",
    },
    "HaeIII": {
        "name": "HaeIII",
        "regexp_for": "GGCC",
        "regexp_rev": "GGCC",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "GGCC",
    },
    "HapII": {
        "name": "HapII",
        "regexp_for": "CCGG",
        "regexp_rev": "CCGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCGG",
    },
    "HgaI": {
        "name": "HgaI",
        "regexp_for": "GACGC",
        "regexp_rev": "GCGTC",
        "skip": 5,
        "overhead_length": 5,
        "recognition_site": "GACGC",
    },
    "HhaI": {
        "name": "HhaI",
        "regexp_for": "GCGC",
        "regexp_rev": "GCGC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GCGC",
    },
    "Hin1I": {
        "name": "Hin1I",
        "regexp_for": "GRCGYC",
        "regexp_rev": "GRCGYC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GRCGYC",
    },
    "Hin1II": {
        "name": "Hin1II",
        "regexp_for": "CATG",
        "regexp_rev": "CATG",
        "skip": 0,
        "overhead_length": 0,
        "recognition_site": "CATG",
    },
    "Hin6I": {
        "name": "Hin6I",
        "regexp_for": "GCGC",
        "regexp_rev": "GCGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCGC",
    },
    "HinP1I": {
        "name": "HinP1I",
        "regexp_for": "GCGC",
        "regexp_rev": "GCGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCGC",
    },
    "HincII": {
        "name": "HincII",
        "regexp_for": "GTYRAC",
        "regexp_rev": "GTYRAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTYRAC",
    },
    "HindIII": {
        "name": "HindIII",
        "regexp_for": "AAGCTT",
        "regexp_rev": "AAGCTT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "AAGCTT",
    },
    "HinfI": {
        "name": "HinfI",
        "regexp_for": "GANTC",
        "regexp_rev": "GANTC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GANTC",
    },
    "HpaI": {
        "name": "HpaI",
        "regexp_for": "GTTAAC",
        "regexp_rev": "GTTAAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTTAAC",
    },
    "HpaII": {
        "name": "HpaII",
        "regexp_for": "CCGG",
        "regexp_rev": "CCGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCGG",
    },
    "HphI": {
        "name": "HphI",
        "regexp_for": "GGTGA",
        "regexp_rev": "TCACC",
        "skip": 8,
        "overhead_length": -1,
        "recognition_site": "GGTGA",
    },
    "Hpy8I": {
        "name": "Hpy8I",
        "regexp_for": "GTNNAC",
        "regexp_rev": "GTNNAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTNNAC",
    },
    "Hpy99I": {
        "name": "Hpy99I",
        "regexp_for": "CGWCG",
        "regexp_rev": "CGWCG",
        "skip": 0,
        "overhead_length": 0,
        "recognition_site": "CGWCG",
    },
    "Hpy166II": {
        "name": "Hpy166II",
        "regexp_for": "GTNNAC",
        "regexp_rev": "GTNNAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTNNAC",
    },
    "Hpy188I": {
        "name": "Hpy188I",
        "regexp_for": "TCNGA",
        "regexp_rev": "TCNGA",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "TCNGA",
    },
    "Hpy188III": {
        "name": "Hpy188III",
        "regexp_for": "TCNNGA",
        "regexp_rev": "TCNNGA",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "TCNNGA",
    },
    "HpyAV": {
        "name": "HpyAV",
        "regexp_for": "CCTTC",
        "regexp_rev": "GAAGG",
        "skip": 6,
        "overhead_length": -1,
        "recognition_site": "CCTTC",
    },
    "HpyCH4III": {
        "name": "HpyCH4III",
        "regexp_for": "ACNGT",
        "regexp_rev": "ACNGT",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "ACNGT",
    },
    "HpyCH4IV": {
        "name": "HpyCH4IV",
        "regexp_for": "ACGT",
        "regexp_rev": "ACGT",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "ACGT",
    },
    "HpyCH4V": {
        "name": "HpyCH4V",
        "regexp_for": "TGCA",
        "regexp_rev": "TGCA",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "TGCA",
    },
    "HpyF3I": {
        "name": "HpyF3I",
        "regexp_for": "CTNAG",
        "regexp_rev": "CTNAG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CTNAG",
    },
    "HpyF10VI": {
        "name": "HpyF10VI",
        "regexp_for": "GCNNNNNNNGC",
        "regexp_rev": "GCNNNNNNNGC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GCNNNNNNNGC",
    },
    "KasI": {
        "name": "KasI",
        "regexp_for": "GGCGCC",
        "regexp_rev": "GGCGCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGCGCC",
    },
    "KflI": {
        "name": "KflI",
        "regexp_for": "GGGWCCC",
        "regexp_rev": "GGGWCCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGGWCCC",
    },
    "KpnI": {
        "name": "KpnI",
        "regexp_for": "GGTACC",
        "regexp_rev": "GGTACC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GGTACC",
    },
    "Kpn2I": {
        "name": "Kpn2I",
        "regexp_for": "TCCGGA",
        "regexp_rev": "TCCGGA",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "TCCGGA",
    },
    "KspAI": {
        "name": "KspAI",
        "regexp_for": "GTTAAC",
        "regexp_rev": "GTTAAC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GTTAAC",
    },
    "LguI": {
        "name": "LguI",
        "regexp_for": "GCTCTTC",
        "regexp_rev": "GAAGAGC",
        "skip": 1,
        "overhead_length": 3,
        "recognition_site": "GCTCTTC",
    },
    "Lsp1109I": {
        "name": "Lsp1109I",
        "regexp_for": "GCAGC",
        "regexp_rev": "GCTGC",
        "skip": 8,
        "overhead_length": 4,
        "recognition_site": "GCAGC",
    },
    "LweI": {
        "name": "LweI",
        "regexp_for": "GCATC",
        "regexp_rev": "GATGC",
        "skip": 5,
        "overhead_length": 4,
        "recognition_site": "GCATC",
    },
    "MauBI": {
        "name": "MauBI",
        "regexp_for": "CGCGCGCG",
        "regexp_rev": "CGCGCGCG",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "CGCGCGCG",
    },
    "MbiI": {
        "name": "MbiI",
        "regexp_for": "CCGCTC",
        "regexp_rev": "GAGCGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCGCTC",
    },
    "MboI": {
        "name": "MboI",
        "regexp_for": "GATC",
        "regexp_rev": "GATC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GATC",
    },
    "MboII": {
        "name": "MboII",
        "regexp_for": "GAAGA",
        "regexp_rev": "TCTTC",
        "skip": 8,
        "overhead_length": -1,
        "recognition_site": "GAAGA",
    },
    "MfeI": {
        "name": "MfeI",
        "regexp_for": "CAATTG",
        "regexp_rev": "CAATTG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CAATTG",
    },
    "MlsI": {
        "name": "MlsI",
        "regexp_for": "TGGCCA",
        "regexp_rev": "TGGCCA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TGGCCA",
    },
    "MluI": {
        "name": "MluI",
        "regexp_for": "ACGCGT",
        "regexp_rev": "ACGCGT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "ACGCGT",
    },
    "MluCI": {
        "name": "MluCI",
        "regexp_for": "AATT",
        "regexp_rev": "AATT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "AATT",
    },
    "MlyI": {
        "name": "MlyI",
        "regexp_for": "GAGTC",
        "regexp_rev": "GACTC",
        "skip": 5,
        "overhead_length": 0,
        "recognition_site": "GAGTC",
    },
    "MmeI": {
        "name": "MmeI",
        "regexp_for": "TCCRAC",
        "regexp_rev": "GTYGGA",
        "skip": 20,
        "overhead_length": -2,
        "recognition_site": "TCCRAC",
    },
    "MnlI": {
        "name": "MnlI",
        "regexp_for": "CCTC",
        "regexp_rev": "GAGG",
        "skip": 7,
        "overhead_length": -1,
        "recognition_site": "CCTC",
    },
    "Mph1103I": {
        "name": "Mph1103I",
        "regexp_for": "ATGCAT",
        "regexp_rev": "ATGCAT",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "ATGCAT",
    },
    "MreI": {
        "name": "MreI",
        "regexp_for": "CGCCGGCG",
        "regexp_rev": "CGCCGGCG",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "CGCCGGCG",
    },
    "MscI": {
        "name": "MscI",
        "regexp_for": "TGGCCA",
        "regexp_rev": "TGGCCA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TGGCCA",
    },
    "MseI": {
        "name": "MseI",
        "regexp_for": "TTAA",
        "regexp_rev": "TTAA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TTAA",
    },
    "MslI": {
        "name": "MslI",
        "regexp_for": "CAYNNNNRTG",
        "regexp_rev": "CAYNNNNRTG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CAYNNNNRTG",
    },
    "MspI": {
        "name": "MspI",
        "regexp_for": "CCGG",
        "regexp_rev": "CCGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCGG",
    },
    "MspA1I": {
        "name": "MspA1I",
        "regexp_for": "CMGCKG",
        "regexp_rev": "CMGCKG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CMGCKG",
    },
    "MspJI": {
        "name": "MspJI",
        "regexp_for": "CNNR",
        "regexp_rev": "YNNG",
        "skip": 9,
        "overhead_length": 4,
        "recognition_site": "CNNR",
    },
    "MssI": {
        "name": "MssI",
        "regexp_for": "GTTTAAAC",
        "regexp_rev": "GTTTAAAC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GTTTAAAC",
    },
    "MunI": {
        "name": "MunI",
        "regexp_for": "CAATTG",
        "regexp_rev": "CAATTG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CAATTG",
    },
    "MvaI": {
        "name": "MvaI",
        "regexp_for": "CCWGG",
        "regexp_rev": "CCWGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCWGG",
    },
    "Mva1269I": {
        "name": "Mva1269I",
        "regexp_for": "GAATGC",
        "regexp_rev": "GCATTC",
        "skip": 1,
        "overhead_length": -2,
        "recognition_site": "GAATGC",
    },
    "MwoI": {
        "name": "MwoI",
        "regexp_for": "GCNNNNNNNGC",
        "regexp_rev": "GCNNNNNNNGC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GCNNNNNNNGC",
    },
    "NaeI": {
        "name": "NaeI",
        "regexp_for": "GCCGGC",
        "regexp_rev": "GCCGGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCCGGC",
    },
    "NarI": {
        "name": "NarI",
        "regexp_for": "GGCGCC",
        "regexp_rev": "GGCGCC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GGCGCC",
    },
    "NciI": {
        "name": "NciI",
        "regexp_for": "CCSGG",
        "regexp_rev": "CCSGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCSGG",
    },
    "NcoI": {
        "name": "NcoI",
        "regexp_for": "CCATGG",
        "regexp_rev": "CCATGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCATGG",
    },
    "NdeI": {
        "name": "NdeI",
        "regexp_for": "CATATG",
        "regexp_rev": "CATATG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CATATG",
    },
    "NgoMIV": {
        "name": "NgoMIV",
        "regexp_for": "GCCGGC",
        "regexp_rev": "GCCGGC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GCCGGC",
    },
    "NheI": {
        "name": "NheI",
        "regexp_for": "GCTAGC",
        "regexp_rev": "GCTAGC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GCTAGC",
    },
    "NlaIII": {
        "name": "NlaIII",
        "regexp_for": "CATG",
        "regexp_rev": "CATG",
        "skip": 0,
        "overhead_length": 0,
        "recognition_site": "CATG",
    },
    "NlaIV": {
        "name": "NlaIV",
        "regexp_for": "GGNNCC",
        "regexp_rev": "GGNNCC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GGNNCC",
    },
    "NmeAIII": {
        "name": "NmeAIII",
        "regexp_for": "GCCGAG",
        "regexp_rev": "CTCGGC",
        "skip": 21,
        "overhead_length": -2,
        "recognition_site": "GCCGAG",
    },
    "NmuCI": {
        "name": "NmuCI",
        "regexp_for": "GTSAC",
        "regexp_rev": "GTSAC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GTSAC",
    },
    "NotI": {
        "name": "NotI",
        "regexp_for": "GCGGCCGC",
        "regexp_rev": "GCGGCCGC",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "GCGGCCGC",
    },
    "NruI": {
        "name": "NruI",
        "regexp_for": "TCGCGA",
        "regexp_rev": "TCGCGA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TCGCGA",
    },
    "NsbI": {
        "name": "NsbI",
        "regexp_for": "TGCGCA",
        "regexp_rev": "TGCGCA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TGCGCA",
    },
    "NsiI": {
        "name": "NsiI",
        "regexp_for": "ATGCAT",
        "regexp_rev": "ATGCAT",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "ATGCAT",
    },
    "NspI": {
        "name": "NspI",
        "regexp_for": "RCATGY",
        "regexp_rev": "RCATGY",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "RCATGY",
    },
    "OliI": {
        "name": "OliI",
        "regexp_for": "CACNNNNGTG",
        "regexp_rev": "CACNNNNGTG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CACNNNNGTG",
    },
    "PacI": {
        "name": "PacI",
        "regexp_for": "TTAATTAA",
        "regexp_rev": "TTAATTAA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TTAATTAA",
    },
    "PaeI": {
        "name": "PaeI",
        "regexp_for": "GCATGC",
        "regexp_rev": "GCATGC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GCATGC",
    },
    "PaeR7I": {
        "name": "PaeR7I",
        "regexp_for": "CTCGAG",
        "regexp_rev": "CTCGAG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CTCGAG",
    },
    "PagI": {
        "name": "PagI",
        "regexp_for": "TCATGA",
        "regexp_rev": "TCATGA",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "TCATGA",
    },
    "PaqCI": {
        "name": "PaqCI",
        "regexp_for": "CACCTGC",
        "regexp_rev": "GCAGGTG",
        "skip": 4,
        "overhead_length": 4,
        "recognition_site": "CACCTGC",
    },
    "PasI": {
        "name": "PasI",
        "regexp_for": "CCCWGGG",
        "regexp_rev": "CCCWGGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCCWGGG",
    },
    "PauI": {
        "name": "PauI",
        "regexp_for": "GCGCGC",
        "regexp_rev": "GCGCGC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GCGCGC",
    },
    "PciI": {
        "name": "PciI",
        "regexp_for": "ACATGT",
        "regexp_rev": "ACATGT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "ACATGT",
    },
    "PdiI": {
        "name": "PdiI",
        "regexp_for": "GCCGGC",
        "regexp_rev": "GCCGGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCCGGC",
    },
    "PdmI": {
        "name": "PdmI",
        "regexp_for": "GAANNNNTTC",
        "regexp_rev": "GAANNNNTTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GAANNNNTTC",
    },
    "PfeI": {
        "name": "PfeI",
        "regexp_for": "GAWTC",
        "regexp_rev": "GAWTC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GAWTC",
    },
    "Pfl23II": {
        "name": "Pfl23II",
        "regexp_for": "CGTACG",
        "regexp_rev": "CGTACG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CGTACG",
    },
    "PflFI": {
        "name": "PflFI",
        "regexp_for": "GACNNNGTC",
        "regexp_rev": "GACNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNGTC",
    },
    "PflMI": {
        "name": "PflMI",
        "regexp_for": "CCANNNNNTGG",
        "regexp_rev": "CCANNNNNTGG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CCANNNNNTGG",
    },
    "PfoI": {
        "name": "PfoI",
        "regexp_for": "TCCNGGA",
        "regexp_rev": "TCCNGGA",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "TCCNGGA",
    },
    "PleI": {
        "name": "PleI",
        "regexp_for": "GAGTC",
        "regexp_rev": "GACTC",
        "skip": 4,
        "overhead_length": 1,
        "recognition_site": "GAGTC",
    },
    "PluTI": {
        "name": "PluTI",
        "regexp_for": "GGCGCC",
        "regexp_rev": "GGCGCC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GGCGCC",
    },
    "PmeI": {
        "name": "PmeI",
        "regexp_for": "GTTTAAAC",
        "regexp_rev": "GTTTAAAC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GTTTAAAC",
    },
    "PmlI": {
        "name": "PmlI",
        "regexp_for": "CACGTG",
        "regexp_rev": "CACGTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CACGTG",
    },
    "Ppu21I": {
        "name": "Ppu21I",
        "regexp_for": "YACGTR",
        "regexp_rev": "YACGTR",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "YACGTR",
    },
    "PpuMI": {
        "name": "PpuMI",
        "regexp_for": "RGGWCCY",
        "regexp_rev": "RGGWCCY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RGGWCCY",
    },
    "PscI": {
        "name": "PscI",
        "regexp_for": "ACATGT",
        "regexp_rev": "ACATGT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "ACATGT",
    },
    "PshAI": {
        "name": "PshAI",
        "regexp_for": "GACNNNNGTC",
        "regexp_rev": "GACNNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNNGTC",
    },
    "PsiI": {
        "name": "PsiI",
        "regexp_for": "TTATAA",
        "regexp_rev": "TTATAA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TTATAA",
    },
    "PI-PspI": {
        "name": "PI-PspI",
        "regexp_for": "TGGCAAACAGCTATTATGGGTATTATGGGT",
        "regexp_rev": "ACCCATAATACCCATAATAGCTGTTTGCCA",
        "skip": -13,
        "overhead_length": -4,
        "recognition_site": "TGGCAAACAGCTATTATGGGTATTATGGGT",
    },
    "Psp5II": {
        "name": "Psp5II",
        "regexp_for": "RGGWCCY",
        "regexp_rev": "RGGWCCY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RGGWCCY",
    },
    "Psp1406I": {
        "name": "Psp1406I",
        "regexp_for": "AACGTT",
        "regexp_rev": "AACGTT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "AACGTT",
    },
    "PspFI": {
        "name": "PspFI",
        "regexp_for": "CCCAGC",
        "regexp_rev": "GCTGGG",
        "skip": -5,
        "overhead_length": 4,
        "recognition_site": "CCCAGC",
    },
    "PspGI": {
        "name": "PspGI",
        "regexp_for": "CCWGG",
        "regexp_rev": "CCWGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCWGG",
    },
    "PspOMI": {
        "name": "PspOMI",
        "regexp_for": "GGGCCC",
        "regexp_rev": "GGGCCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGGCCC",
    },
    "PspXI": {
        "name": "PspXI",
        "regexp_for": "VCTCGAGB",
        "regexp_rev": "VCTCGAGB",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "VCTCGAGB",
    },
    "PstI": {
        "name": "PstI",
        "regexp_for": "CTGCAG",
        "regexp_rev": "CTGCAG",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "CTGCAG",
    },
    "PsuI": {
        "name": "PsuI",
        "regexp_for": "RGATCY",
        "regexp_rev": "RGATCY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RGATCY",
    },
    "PsyI": {
        "name": "PsyI",
        "regexp_for": "GACNNNGTC",
        "regexp_rev": "GACNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNGTC",
    },
    "PteI": {
        "name": "PteI",
        "regexp_for": "GCGCGC",
        "regexp_rev": "GCGCGC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GCGCGC",
    },
    "PvuI": {
        "name": "PvuI",
        "regexp_for": "CGATCG",
        "regexp_rev": "CGATCG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CGATCG",
    },
    "PvuII": {
        "name": "PvuII",
        "regexp_for": "CAGCTG",
        "regexp_rev": "CAGCTG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CAGCTG",
    },
    "RruI": {
        "name": "RruI",
        "regexp_for": "TCGCGA",
        "regexp_rev": "TCGCGA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TCGCGA",
    },
    "RsaI": {
        "name": "RsaI",
        "regexp_for": "GTAC",
        "regexp_rev": "GTAC",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "GTAC",
    },
    "RseI": {
        "name": "RseI",
        "regexp_for": "CAYNNNNRTG",
        "regexp_rev": "CAYNNNNRTG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CAYNNNNRTG",
    },
    "RsrII": {
        "name": "RsrII",
        "regexp_for": "CGGWCCG",
        "regexp_rev": "CGGWCCG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CGGWCCG",
    },
    "SacI": {
        "name": "SacI",
        "regexp_for": "GAGCTC",
        "regexp_rev": "GAGCTC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GAGCTC",
    },
    "SacII": {
        "name": "SacII",
        "regexp_for": "CCGCGG",
        "regexp_rev": "CCGCGG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CCGCGG",
    },
    "SalI": {
        "name": "SalI",
        "regexp_for": "GTCGAC",
        "regexp_rev": "GTCGAC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GTCGAC",
    },
    "SapI": {
        "name": "SapI",
        "regexp_for": "GCTCTTC",
        "regexp_rev": "GAAGAGC",
        "skip": 1,
        "overhead_length": 3,
        "recognition_site": "GCTCTTC",
    },
    "SaqAI": {
        "name": "SaqAI",
        "regexp_for": "TTAA",
        "regexp_rev": "TTAA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TTAA",
    },
    "SatI": {
        "name": "SatI",
        "regexp_for": "GCNGC",
        "regexp_rev": "GCNGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCNGC",
    },
    "Sau96I": {
        "name": "Sau96I",
        "regexp_for": "GGNCC",
        "regexp_rev": "GGNCC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GGNCC",
    },
    "Sau3AI": {
        "name": "Sau3AI",
        "regexp_for": "GATC",
        "regexp_rev": "GATC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GATC",
    },
    "SbfI": {
        "name": "SbfI",
        "regexp_for": "CCTGCAGG",
        "regexp_rev": "CCTGCAGG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CCTGCAGG",
    },
    "ScaI": {
        "name": "ScaI",
        "regexp_for": "AGTACT",
        "regexp_rev": "AGTACT",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "AGTACT",
    },
    "I-SceI": {
        "name": "I-SceI",
        "regexp_for": "TAGGGATAACAGGGTAAT",
        "regexp_rev": "ATTACCCTGTTATCCCTA",
        "skip": -9,
        "overhead_length": -4,
        "recognition_site": "TAGGGATAACAGGGTAAT",
    },
    "PI-SceI": {
        "name": "PI-SceI",
        "regexp_for": "ATCTATGTCGGGTGCGGAGAAAGAGGTAATGAAATGG",
        "regexp_rev": "CCATTTCATTACCTCTTTCTCCGCACCCGACATAGAT",
        "skip": -22,
        "overhead_length": -4,
        "recognition_site": "ATCTATGTCGGGTGCGGAGAAAGAGGTAATGAAATGG",
    },
    "SchI": {
        "name": "SchI",
        "regexp_for": "GAGTC",
        "regexp_rev": "GACTC",
        "skip": 5,
        "overhead_length": 0,
        "recognition_site": "GAGTC",
    },
    "ScrFI": {
        "name": "ScrFI",
        "regexp_for": "CCNGG",
        "regexp_rev": "CCNGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCNGG",
    },
    "SdaI": {
        "name": "SdaI",
        "regexp_for": "CCTGCAGG",
        "regexp_rev": "CCTGCAGG",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "CCTGCAGG",
    },
    "SduI": {
        "name": "SduI",
        "regexp_for": "GDGCHC",
        "regexp_rev": "GDGCHC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GDGCHC",
    },
    "SexAI": {
        "name": "SexAI",
        "regexp_for": "ACCWGGT",
        "regexp_rev": "ACCWGGT",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "ACCWGGT",
    },
    "SfaAI": {
        "name": "SfaAI",
        "regexp_for": "GCGATCGC",
        "regexp_rev": "GCGATCGC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GCGATCGC",
    },
    "SfaNI": {
        "name": "SfaNI",
        "regexp_for": "GCATC",
        "regexp_rev": "GATGC",
        "skip": 5,
        "overhead_length": 4,
        "recognition_site": "GCATC",
    },
    "SfcI": {
        "name": "SfcI",
        "regexp_for": "CTRYAG",
        "regexp_rev": "CTRYAG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CTRYAG",
    },
    "SfiI": {
        "name": "SfiI",
        "regexp_for": "GGCCNNNNNGGCC",
        "regexp_rev": "GGCCNNNNNGGCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGCCNNNNNGGCC",
    },
    "SfoI": {
        "name": "SfoI",
        "regexp_for": "GGCGCC",
        "regexp_rev": "GGCGCC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GGCGCC",
    },
    "SgeI": {
        "name": "SgeI",
        "regexp_for": "CNNGNNNNNNNNN",
        "regexp_rev": "NNNNNNNNNCNNG",
        "skip": 0,
        "overhead_length": 0,
        "recognition_site": "CNNGNNNNNNNNN",
    },
    "SgrAI": {
        "name": "SgrAI",
        "regexp_for": "CRCCGGYG",
        "regexp_rev": "CRCCGGYG",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "CRCCGGYG",
    },
    "SgrDI": {
        "name": "SgrDI",
        "regexp_for": "CGTCGACG",
        "regexp_rev": "CGTCGACG",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "CGTCGACG",
    },
    "SgsI": {
        "name": "SgsI",
        "regexp_for": "GGCGCGCC",
        "regexp_rev": "GGCGCGCC",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "GGCGCGCC",
    },
    "SmaI": {
        "name": "SmaI",
        "regexp_for": "CCCGGG",
        "regexp_rev": "CCCGGG",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "CCCGGG",
    },
    "SmiI": {
        "name": "SmiI",
        "regexp_for": "ATTTAAAT",
        "regexp_rev": "ATTTAAAT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "ATTTAAAT",
    },
    "SmlI": {
        "name": "SmlI",
        "regexp_for": "CTYRAG",
        "regexp_rev": "CTYRAG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CTYRAG",
    },
    "SmoI": {
        "name": "SmoI",
        "regexp_for": "CTYRAG",
        "regexp_rev": "CTYRAG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CTYRAG",
    },
    "SnaBI": {
        "name": "SnaBI",
        "regexp_for": "TACGTA",
        "regexp_rev": "TACGTA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TACGTA",
    },
    "SpeI": {
        "name": "SpeI",
        "regexp_for": "ACTAGT",
        "regexp_rev": "ACTAGT",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "ACTAGT",
    },
    "SphI": {
        "name": "SphI",
        "regexp_for": "GCATGC",
        "regexp_rev": "GCATGC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GCATGC",
    },
    "SrfI": {
        "name": "SrfI",
        "regexp_for": "GCCCGGGC",
        "regexp_rev": "GCCCGGGC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GCCCGGGC",
    },
    "SsiI": {
        "name": "SsiI",
        "regexp_for": "CCGC",
        "regexp_rev": "GCGG",
        "skip": -3,
        "overhead_length": 2,
        "recognition_site": "CCGC",
    },
    "SspI": {
        "name": "SspI",
        "regexp_for": "AATATT",
        "regexp_rev": "AATATT",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "AATATT",
    },
    "SspDI": {
        "name": "SspDI",
        "regexp_for": "GGCGCC",
        "regexp_rev": "GGCGCC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GGCGCC",
    },
    "StuI": {
        "name": "StuI",
        "regexp_for": "AGGCCT",
        "regexp_rev": "AGGCCT",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "AGGCCT",
    },
    "StyI": {
        "name": "StyI",
        "regexp_for": "CCWWGG",
        "regexp_rev": "CCWWGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCWWGG",
    },
    "StyD4I": {
        "name": "StyD4I",
        "regexp_for": "CCNGG",
        "regexp_rev": "CCNGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCNGG",
    },
    "SwaI": {
        "name": "SwaI",
        "regexp_for": "ATTTAAAT",
        "regexp_rev": "ATTTAAAT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "ATTTAAAT",
    },
    "TaaI": {
        "name": "TaaI",
        "regexp_for": "ACNGT",
        "regexp_rev": "ACNGT",
        "skip": -2,
        "overhead_length": 0,
        "recognition_site": "ACNGT",
    },
    "TaiI": {
        "name": "TaiI",
        "regexp_for": "ACGT",
        "regexp_rev": "ACGT",
        "skip": 0,
        "overhead_length": 0,
        "recognition_site": "ACGT",
    },
    "TaqI": {
        "name": "TaqI",
        "regexp_for": "TCGA",
        "regexp_rev": "TCGA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TCGA",
    },
    "TasI": {
        "name": "TasI",
        "regexp_for": "AATT",
        "regexp_rev": "AATT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "AATT",
    },
    "TatI": {
        "name": "TatI",
        "regexp_for": "WGTACW",
        "regexp_rev": "WGTACW",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "WGTACW",
    },
    "TauI": {
        "name": "TauI",
        "regexp_for": "GCSGC",
        "regexp_rev": "GCSGC",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "GCSGC",
    },
    "TfiI": {
        "name": "TfiI",
        "regexp_for": "GAWTC",
        "regexp_rev": "GAWTC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GAWTC",
    },
    "Tru1I": {
        "name": "Tru1I",
        "regexp_for": "TTAA",
        "regexp_rev": "TTAA",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "TTAA",
    },
    "TscAI": {
        "name": "TscAI",
        "regexp_for": "CASTGNN",
        "regexp_rev": "NNCASTG",
        "skip": 0,
        "overhead_length": 0,
        "recognition_site": "CASTGNN",
    },
    "TseI": {
        "name": "TseI",
        "regexp_for": "GCWGC",
        "regexp_rev": "GCWGC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GCWGC",
    },
    "Tsp45I": {
        "name": "Tsp45I",
        "regexp_for": "GTSAC",
        "regexp_rev": "GTSAC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GTSAC",
    },
    "TspMI": {
        "name": "TspMI",
        "regexp_for": "CCCGGG",
        "regexp_rev": "CCCGGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCCGGG",
    },
    "TspRI": {
        "name": "TspRI",
        "regexp_for": "CASTGNN",
        "regexp_rev": "NNCASTG",
        "skip": 0,
        "overhead_length": 0,
        "recognition_site": "CASTGNN",
    },
    "Tth111I": {
        "name": "Tth111I",
        "regexp_for": "GACNNNGTC",
        "regexp_rev": "GACNNNGTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GACNNNGTC",
    },
    "Van91I": {
        "name": "Van91I",
        "regexp_for": "CCANNNNNTGG",
        "regexp_rev": "CCANNNNNTGG",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "CCANNNNNTGG",
    },
    "VspI": {
        "name": "VspI",
        "regexp_for": "ATTAAT",
        "regexp_rev": "ATTAAT",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "ATTAAT",
    },
    "XagI": {
        "name": "XagI",
        "regexp_for": "CCTNNNNNAGG",
        "regexp_rev": "CCTNNNNNAGG",
        "skip": -6,
        "overhead_length": 0,
        "recognition_site": "CCTNNNNNAGG",
    },
    "XapI": {
        "name": "XapI",
        "regexp_for": "RAATTY",
        "regexp_rev": "RAATTY",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "RAATTY",
    },
    "XbaI": {
        "name": "XbaI",
        "regexp_for": "TCTAGA",
        "regexp_rev": "TCTAGA",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "TCTAGA",
    },
    "XceI": {
        "name": "XceI",
        "regexp_for": "RCATGY",
        "regexp_rev": "RCATGY",
        "skip": -1,
        "overhead_length": 0,
        "recognition_site": "RCATGY",
    },
    "XcmI": {
        "name": "XcmI",
        "regexp_for": "CCANNNNNNNNNTGG",
        "regexp_rev": "CCANNNNNNNNNTGG",
        "skip": -7,
        "overhead_length": 0,
        "recognition_site": "CCANNNNNNNNNTGG",
    },
    "XhoI": {
        "name": "XhoI",
        "regexp_for": "CTCGAG",
        "regexp_rev": "CTCGAG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CTCGAG",
    },
    "XmaI": {
        "name": "XmaI",
        "regexp_for": "CCCGGG",
        "regexp_rev": "CCCGGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCCGGG",
    },
    "XmaJI": {
        "name": "XmaJI",
        "regexp_for": "CCTAGG",
        "regexp_rev": "CCTAGG",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "CCTAGG",
    },
    "XmiI": {
        "name": "XmiI",
        "regexp_for": "GTMKAC",
        "regexp_rev": "GTMKAC",
        "skip": -4,
        "overhead_length": 0,
        "recognition_site": "GTMKAC",
    },
    "XmnI": {
        "name": "XmnI",
        "regexp_for": "GAANNNNTTC",
        "regexp_rev": "GAANNNNTTC",
        "skip": -5,
        "overhead_length": 0,
        "recognition_site": "GAANNNNTTC",
    },
    "ZraI": {
        "name": "ZraI",
        "regexp_for": "GACGTC",
        "regexp_rev": "GACGTC",
        "skip": -3,
        "overhead_length": 0,
        "recognition_site": "GACGTC",
    },
}

# Build the Aho-Corasick automaton
# for matching
ENZYME_MATCHER = ahocorasick.Automaton()
for e in ENZYMES.values():
    # the bool is if it was a forward or reverse match
    # add_word(key word, value that we get back)
    ENZYME_MATCHER.add_word(e["regexp_for"], (e, True))
    if e["regexp_for"] != e["regexp_rev"]:
        ENZYME_MATCHER.add_word(e["regexp_rev"], (e, False))
ENZYME_MATCHER.make_automaton()
