name: docs

on:
  push:
    branches:
      - main  # Change to your default branch
      - docs
  pull_request:
    branches:
      - main  # Optional: build on pull requests to the main branch
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme

    - name: Build the Sphinx documentation
      working-directory: ./docs
      run: make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
